### ISSUE TITLE
Maya Asset Browser

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-magenta#44]
We'll need a way to get assets into Maya without fuzz.
### Responsibilities

It should handle:
- Listing assets of the current project, e.g. `thedeal/assets/*.*`
- Importing as referencing the selected asset
- Append namespace to imported asset, e.g. `ben_`
- Apply environment variables to absolute path, e.g. `$PROJECTROOT/assets/...`
- Add data to reference node, for [lazy referencing](http://forums.pyblish.com/t/lazy-reference/154).
  
  ``` yaml
  project: "hulk"
  asset: "bruce"
  task: "animRig"
  family: "rig"
  instance: "bruce"
  version: "v032"
  ```
### Graphics

Visually it needn't be much more complicated than..

```
 _____________________
|_____________________|
| ben                 |
| - model             |
| - rig               |
| jerry               |
| - model             |
| - rig               |
| chair               |
| - model             |
| - rig               |
| table               |
| - model             |
| - rig               |
|_____________________|
|               Load  |
|_____________________|

It's mostly about functionality at this point.
```
